### PR TITLE
Allow to filter restricted nodes

### PR DESCRIPTION
**Pull request by soffokl**

### CODE REVIEW

**Review by tomasmik — APPROVED** [review]

**Comment by Snawoot** [comment]
I suppose this PR aimed to hide providers with NAT inpenetrable by consumer. Consumers with symmetric NAT will be able to use providers with restricted cone nat or better. Consumers with port restricted nat will be able to use providers with port restricted cone nat or better. For this reason we need exact nat type in proposal, not just boolean value.

**Comment by soffokl** [comment]
Consumers with symmetric NAT cannot connect to providers with port restricted NAT. Other consumers can connect. Looks boolean.

**Comment by Snawoot** [comment]
@soffokl 

If we'll mark all providers with "port restricted nat" or "symmetric nat" as "restricted" then we'll have bad situation for consumers which have "port restricted nat": they are be able to connect to providers with "port restricted nat" but not able to connect to providers with "symmetric nat".

**Review by mdomasevicius — APPROVED** [review]
Seems like .gitlab-ci.yml is present but actual pipeline is not hooked up on our gitlab... :( Mind running e2e test on your machine?

**Review by vkuznecovas — APPROVED** [review]

**Review by mdomasevicius — APPROVED** [review]

**Pull request merged**
